### ISSUE TITLE
what is input['gt_0']?

### ISSUE THREAD

**Issue by zhouwer** [zxyemo/EvUnroll#1]
hi:
what is input['gt_0'] in function loss_fn_flow( )  in trainer.py?
thank you.

**Comment by zxyemo** [comment]
Sorry for my late reply. input['gt_0'] is the GS frame corresponding to timestamp 0, i.e. the exposure begin of the first row of the RS frame. I found that adding constraints to the predicted gs flow will make the training process more stable.

**Comment by zhouwer** [comment]
Thank you very much, it doesn't matter, but I found it doesn't exist in the datasets, so how to train it? The second question is about datasets, one RS frame corresponds to one GT frame, if the exposure time of one RS frame is from timestamp=0 to timestamp=1，then the timestamp of GT frame should be timestamp=0.5, right? If so, model is not trained at timestamp !=0.5, because GT frame at timestamp !=0.5 doesn't exist, datasets only have GT frame at timestamp=0.5, right? So, why can the model restore the GS image at any timestamp in the exposure period of the input RS image? In other words, the quality of restore the GS image at timestamp=0.5 is better than that of restore the GS image at timestamp=0.1 or 0.2... (timestamp !=0.5),right?
Look forward to your kind advice, thank you very much!!!

**Comment by zhouwer** [comment]
Thank you very much, it doesn't matter, but I found it doesn't exist in the datasets, so how to train it? The second question is about datasets, one RS frame corresponds to one GT frame, if the exposure time of one RS frame is from timestamp=0 to timestamp=1，then the timestamp of GT frame should be timestamp=0.5, right? If so, model is not trained at timestamp !=0.5, because GT frame at timestamp !=0.5 doesn't exist, datasets only have GT frame at timestamp=0.5, right? So, why can the model restore the GS image at any timestamp in the exposure period of the input RS image? In other words, the quality of restore the GS image at timestamp=0.5 is better than that of restore the GS image at timestamp=0.1 or 0.2... (timestamp !=0.5),right?
Look forward to your kind advice, thank you very much!!!




空中灵鹫
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zxyemo/EvUnroll"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月4日(星期六) 凌晨1:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zxyemo/EvUnroll] what is input['gt_0']? (Issue #1)





 
Sorry for my late reply. input['gt_0'] is the GS frame corresponding to timestamp 0, i.e. the exposure begin of the first row of the RS frame. I found that adding constraints to the predicted gs flow will make the training process more stable.

**Comment by blt-NOP** [comment]
i want to know what kind of information is stored in gt_root which path to the ground truth images. and what should i do with the 'all_sequence'?
